DISTRO = "demo"
DISTRO_NAME = "Yocto RPi4 RAUC Demo"
DISTRO_VERSION = "0.1.0"

DISTRO_FEATURES:append = " systemd pam rauc"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"
