PermitRootLogin no
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes

AllowUsers demo
MaxAuthTries 3
LoginGraceTime 20
ClientAliveInterval 300
ClientAliveCountMax 2

LogLevel VERBOSE
