require conf/machine/raspberrypi4-64.conf

GPU_MEM = "16"
ENABLE_I2C = "1"
ENABLE_SPI = "1"
ENABLE_UART = "1"

RPI_USE_U_BOOT = "1"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"

WKS_FILE = "sdimage-dual-raspberrypi.wks.in"
